version: "3.8"

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: gitlab.redlabs.local
    ports:
      - "80:80"
      - "443:443"
      - "2222:22"
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.redlabs.local' 1 
        gitlab_rails['gitlab_shell_ssh_port'] = 2222

  keycloak:
    image: keycloak/keycloak:latest
    hostname: keycloak.redlabs.local
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
      - KEYCLOAK_IMPORT=/tmp/realm-export.json
    volumes:
      - ./keycloak/realm-export.json:/tmp/realm-export.json

  defectdojo:
    image: defectdojo/defectdojo:latest
    hostname: defectdojo.redlabs.local
    ports:
      - "8082:80"
    volumes:
      - ./defectdojo/data:/data
    environment:
      - DJANGO_DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1,defectdojo.redlabs.local
      - SECRET_KEY=YourSecretKey
      - DJANGO_SETTINGS_MODULE=dojo.settings

  goharbor-db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: goharbor
      POSTGRES_PASSWORD: goharbor_db_password
      POSTGRES_DB: goharbor
    volumes:
      - ./goharbor-db/data:/var/lib/postgresql/data

  goharbor-core:
    image: goharbor/harbor-core:v2.8.0
    restart: always
    depends_on:
      - goharbor-db
    environment:
      HARBOR_ADMIN_PASSWORD: Harbor12345
      POSTGRESQL_HOST: goharbor-db
      POSTGRESQL_PORT: 5432
      POSTGRESQL_DATABASE: goharbor
      POSTGRESQL_USERNAME: goharbor
      POSTGRESQL_PASSWORD: goharbor_db_password
    volumes:
      - ./goharbor-core/config:/etc/core
      - ./goharbor-core/common/config:/common/config

  goharbor-portal:
    image: goharbor/harbor-portal:v2.8.0
    restart: always
    depends_on:
      - goharbor-core
    environment:
      CORE_SECRET: goharbor_core_secret
    volumes:
      - ./goharbor-portal/config:/etc/portal

  goharbor-jobservice:
    image: goharbor/harbor-jobservice:v2.8.0
    restart: always
    depends_on:
      - goharbor-core
    environment:
      CORE_SECRET: goharbor_core_secret
      REDIS_HOST: goharbor-redis
      REDIS_PASSWORD: ""
    volumes:
      - ./goharbor-jobservice/config:/etc/jobservice

  goharbor-redis:
    image: redis:alpine
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./goharbor-redis/data:/data
      - ./goharbor-redis/redis.conf:/usr/local/etc/redis/redis.conf

networks:
  default:
    external:
      name: redlabs-network
